// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// GenerateAccessToken provides a mock function with no fields
func (_m *AuthService) GenerateAccessToken() (*string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func() (*string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCachedActionUserAccessToken provides a mock function with no fields
func (_m *AuthService) GetCachedActionUserAccessToken() *string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCachedActionUserAccessToken")
	}

	var r0 *string
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// VerifyActionUserToken provides a mock function with given fields: token
func (_m *AuthService) VerifyActionUserToken(token string) (bool, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyActionUserToken")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyUserToken provides a mock function with given fields: userToken
func (_m *AuthService) VerifyUserToken(userToken string) (bool, bool) {
	ret := _m.Called(userToken)

	if len(ret) == 0 {
		panic("no return value specified for VerifyUserToken")
	}

	var r0 bool
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (bool, bool)); ok {
		return rf(userToken)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(userToken)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(userToken)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
