// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	models "polling_websocket/pkg/domain/models"

	mock "github.com/stretchr/testify/mock"
)

// CredentialBrokerRepository is an autogenerated mock type for the CredentialBrokerRepository type
type CredentialBrokerRepository struct {
	mock.Mock
}

func (_m *CredentialBrokerRepository) Close() {
	_m.Called()
}

// UpdateCredential provides a mock function with given fields: exchangeCredential
func (_m *CredentialBrokerRepository) UpdateCredential(exchangeCredential *models.RequestExchangeCredential) bool {
	ret := _m.Called(exchangeCredential)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCredential")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*models.RequestExchangeCredential) bool); ok {
		r0 = rf(exchangeCredential)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewCredentialBrokerRepository creates a new instance of CredentialBrokerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialBrokerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialBrokerRepository {
	mock := &CredentialBrokerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
