// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	models "polling_websocket/pkg/domain/models"

	mock "github.com/stretchr/testify/mock"
)

// PollingBrokerRepository is an autogenerated mock type for the PollingBrokerRepository type
type PollingBrokerRepository struct {
	mock.Mock
}

// SendAction provides a mock function with given fields: newAction
func (_m *PollingBrokerRepository) SendAction(newAction *models.RequestGoogleAction) bool {
	ret := _m.Called(newAction)

	if len(ret) == 0 {
		panic("no return value specified for SendAction")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*models.RequestGoogleAction) bool); ok {
		r0 = rf(newAction)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewPollingBrokerRepository creates a new instance of PollingBrokerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPollingBrokerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PollingBrokerRepository {
	mock := &PollingBrokerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
